name: Validate Terraform examples

on:
  push:
    branches: [ develop, main ]
    paths:
      - ".github/workflows/terraform_examples.yml"
  pull_request:
    branches: [ develop, main ]
    paths:
      - "docs/ejemplos-terraform/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutS
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive docs/ejemplos-terraform

      - name: Terraform init (no backend)
        run: terraform -chdir=docs/ejemplos-terraform init -backend=false

      - name: Terraform validate
        run: terraform -chdir=docs/ejemplos-terraform validate
